### ISSUE TITLE
Error when installing SOS with system encoding different than UTF-8

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#1179]
The installation fails during finishing installation when creating/updating the database model with `java.nio.charset.MalformedInputException: Input length = 1`.

This issue occurs probably if the system/jvm default encoding is not UTF-8 (or similar). The SOS (hibernate) writes the script to a file and then reads the file for execution. The file is written in the JVM default charset and read in UTF-8.

Solution: Define `AvailableSettings.HBM2DDL_CHARSET_NAME` to write the file in UTF-8.

**Comment by subhamgcon** [comment]
Hey, I am a complete beginner to open source and I want to get started by working on this issue. Can you help me with it? @CarstenHollmann

**Comment by CarstenHollmann** [comment]
Fixed in version v5.2.11 and 5.4.2
