### ISSUE TITLE
Harvesting 52°North SOS with Geonetwork

### ISSUE THREAD

**Issue by cWam-zz** [52North/SOS#1310]
Hello,
I try to harvest a 52°North SOS with Geonetwork but this does not work with my own service because it seems that Geonetwork add a VERSION paramater in the GetCapabilities request. However, when harvesting a demo 52°North SOS works well.
Indeed, the following address in a web browser works well : http://dev.demo.i52nsos.axiomdatascience.com/sos/kvp?service=SOS&request=GetCapabilities&AcceptVersions=1.0.0&SERVICE=SOS&VERSION=1.0.0
whereas  an exception is raised when using my service : http://localhost:8080/SOS/service?service=SOS&request=GetCapabilities&AcceptVersions=1.0.0&SERVICE=SOS&VERSION=1.0.0
<ows:ExceptionText>The requested operation 'GetCapabilities' is not supported by this service!</ows:ExceptionText>

A similar result is provided when using the 52°North demo : http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities&VERSION=1.0.0

I would like to known how to enable a VERSION parameter in the GetCapabilities SOS request even if this is not used to get the GetCapabilities response (because VERSION is not a parameter for the SOS GetCapabilities request).

I currently use 52°North 5.2.11 or 5.4.2 (in test).

Thanks a lot for information you could provide.
Best regards.

NB : An issue has been posted in for Geonetwork (https://github.com/geonetwork/core-geonetwork/issues/6273).

**Comment by CarstenHollmann** [comment]
The current 52°North demo SOS and the SOS from axiomdatascience,com are 52N SOS version 4.x. In version 5.x the SOS as refactored and some parts were extracted into the [arctic-sea](https://github.com/52North/arctic-sea) project. This refactoring includes some major changes and it looks like the the previously working _not specified_ `version` parameter has changed.
We have fixed this an with this commit ca737c9812a57820da7027a27164b2d51fe3927d the KVP GetCapabilities with `version=1.0.0` parameter does not throw an exception. This fix is part of the new [v5.4.3](https://github.com/52North/SOS/releases/tag/v5.4.3) release of the 52N SOS .

**Comment by cWam-zz** [comment]
Dear Carsten,
Harvesting the new version you suggested (52°North SOS 5.4.3) with Geonetwork works well now. Using the VERSION parameter is now allowed.

Thanks a lot.
Best regards.
