### ISSUE TITLE
Laxer checking of output format

### ISSUE THREAD

**Issue by nuest** [52North/SOS#168]
DescribeSensor requests fail if there is a space in the outputFormat or not. For background see
http://geostatistics.forum.52north.org/Encoding-of-parameter-in-describeSensor-request-in-sos4R-tp4022931p4022947.html

**Is the space in the output format definition really required?** I didn't find a specification for that, but I would expect that the following two work the same way and are supported by the SOS:

* ``text/xml; subtype="sensorML/1.0.1"`` 
* ``text/xml;subtype="sensorML/1.0.1"``

**Comment by CarstenHollmann** [comment]
Fixed in https://github.com/52North/SOS/pull/169
