### ISSUE TITLE
JSON GetFeatureOfInterest request ignores the observedProperty parameter

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#172]
If you send a JSON GetFeatureOfInterest request with observedProperty parameter, the SOS does not consider the observedProperty.

The JSON-GetFeatureOfInterestRequestDecoder checks for **observableProperty** instead of **observedProperty**
https://github.com/52North/SOS/blob/develop/coding/json/src/main/java/org/n52/sos/decode/json/impl/GetFeatureOfInterestRequestDecoder.java#L88-93

**Comment by autermann** [comment]
Fixed in #184.
