### ISSUE TITLE
HOST_DESCRIPTION is used for DATABASE_DESCRIPTION

### ISSUE THREAD

**Issue by johnjohndoe** [52North/SOS#173]
I noticed from the setup that the description text for the *Database* configuration is the same as the text for the *Host* configuration. This can been seen in the screenshot.

![sos-setup](https://cloud.githubusercontent.com/assets/144518/6482374/79359ce2-c265-11e4-97a7-9dc53e0b536a.png)

The source of the problem might be a copy/paste error as one can see from [searching for `HOST_DESCRIPTION` in the sources](https://github.com/52North/SOS/search?utf8=%E2%9C%93&q=HOST_DESCRIPTION).

**Comment by autermann** [comment]
Fixed it, thanks for reporting!

**Comment by johnjohndoe** [comment]
Thanks for open sourcing! Is [this](https://github.com/52North/SOS/commit/76cef3ec9d429cf6338f2be17e7be0d30b98f5e0#diff-4271401967794b4bb3ec8540f9455e0bL48) the only location? 

---
Is there any way I could send you improvements for your website/documentation?

**Comment by EHJ-52n** [comment]
@johnjohndoe Write an email to it-support@52north.org if you find any issues on our website in general.

If you are talking about the SOS homepage, feel free to write an mail to swe@52north.org or it-support@52north.org, too.
