### ISSUE TITLE
Change default branch to develop

### ISSUE THREAD

**Issue by autermann** [52North/SOS#179]
Small fixes (to e.g. the `README.md`, see #177 and #178) are only visible after the change is merged into `master`, i.e. a new SOS release. Therefore I would propose to change the default branch of the repository to the `develop` branch, as visitors would directly see the latest version...

**Comment by nuest** [comment]
+1

**Comment by EHJ-52n** [comment]
On 08.03.2015 17:34, Daniel Nüst wrote:
>
> +1
>
+1

but in that case we should add some hints in the README.md that the
current version is the latest development version and not the latest
release.

-- 
Eike Hinderk Jürrens
52°North Initiative for Geospatial Open Source Software GmbH
Martin-Luther-King-Weg 24
48155 Münster, Germany
E-Mail: e.h.juerrens@52north.org
Fon: +49-(0)-251–396371-33
Fax: +49-(0)-251–396371-11
http://52north.org/
Twitter: @FiveTwoN
General Managers: Dr. Albert Remke, Dr. Andreas Wytzisk
Local Court Muenster HRB 10849

**Comment by autermann** [comment]
> but in that case we should add some hints in the README.md that the
> current version is the latest development version and not the latest
> release.

Isn't that the case for nearly every software repository?

**Comment by CarstenHollmann** [comment]
I have changed the default branch to ´´´develop´´´ and the ´´´master´´´ branch is now protected.
