### ISSUE TITLE
Empty content in response to DescribeSensor, only in case of sensorML 1.0.1

### ISSUE THREAD

**Issue by meliezer** [52North/SOS#203]
Hello,
The response:
200 OK
Date: Fri, 27 Mar 2015 13:22:19 GMT
Content-Encoding: gzip
Server: Apache/2.4.10 (Debian)
Connection: Keep-Alive
Keep-Alive: timeout=5, max=100
Content-Length: 20
Content-Type: application/json;charset=UTF-8

The request:
{
  "request": "DescribeSensor",
  "service": "SOS",
  "version": "2.0.0",
  "procedure": "urn:ogc:object:feature:Sensor:OGS:CT_10597_E2M3A",
  "procedureDescriptionFormat": "http://www.opengis.net/sensorML/1.0.1"
}

However, in case of "http://www.opengis.net/sensorml/2.0" I do get a good response.

Debian 8, Tomcat 8, Java: Oracle 1.8.0_20-b26 
sensorwebclient-webapp-3.3.0-rc.3-SNAPSHOT working with SOS 4.2.0 (Master branch) at http://nodc.ogs.trieste.it/SOS42/sos , using SOS 2.0.0.

--
Menashè

**Comment by CarstenHollmann** [comment]
What is the default procedureDescriptionFormat of the procedure?
Would it be possible to provide the InsertSensor request of this procedure?

**Comment by meliezer** [comment]
>What is the default procedureDescriptionFormat of the procedure?
Where can I find this parameter? Maybe you mean the format in which was inserted this sensor: SensorML 2.0.
For testing we've copied without changes the InsertSensor example for SensorML 2.0 (POX binding) from the test client, and I can easily reproduce the above issue with http://www.52north.org/test/procedure/9
I assume you can also see it asking our SOS:http://nodc.ogs.trieste.it/SOS42/service

**Comment by meliezer** [comment]
I'm closing this issue due to an error.
