### ISSUE TITLE
The HTTP-Accept header contains an invalid value:  *; q=.2

### ISSUE THREAD

**Issue by meliezer** [52North/SOS#204]
Hello,
SOS 4.2.0 (Master branch), every 30 minutes I see the following warning in log:
The HTTP-Accept header contains an invalid value:  *; q=.2

All I have is this error. I have no idea what is the context.

--
Menashè

**Comment by autermann** [comment]
Sounds like somebody is requesting the SOS endpoint from a web browser which sends `*; q=.2` in the `Accept` header. But that is only a warning, the part of the header is hust [ignored](https://github.com/52North/SOS/blob/4f7672ecb1d1443b7de3145204dbea8fd0bd47bc/core/api/src/main/java/org/n52/sos/util/http/HTTPUtils.java#L106).

**Comment by meliezer** [comment]
Thank you. I have no explanation, but I can ignore these lines.
