### ISSUE TITLE
Guidance for data sources configuration requested

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#209]
We would like to test 52North SOS service. SOS Documentation is great for installing and also for describing services but we have still doubts on how to deal with data sources.

All our sensor data is being storing mostly in a database with custom schema (generated from proprietary SCADA). 

What would be the most streamlined way to feed SOS own database? SOS T-Interface seems a bit overkill for updating observations.

**Comment by EHJ-52n** [comment]
@jruizaranguren You might add a sentence or two why you closed this issue. Maybe you can tell the world what your solution about this topic is.

**Comment by autermann** [comment]
Solution was to ask on the [mailing list](http://sensorweb.forum.52north.org/Inserting-data-to-52North-td4027938.html).
