### ISSUE TITLE
default_settings.db vs default_settings.sql

### ISSUE THREAD

**Issue by shane-axiom** [52North/SOS#224]
[default_settings.sql](https://github.com/52North/SOS/blob/master/misc/db/default_settings.sql) seems to not be getting updated anymore with new settings and is lacking many of the tables and settings present in [default_settings.db](https://github.com/52North/SOS/blob/master/misc/conf/default_settings.db).

For example, default_settings.sql is missing the following tables:
* bindings                           
* capabilities_extension          
* choice_settings                   
* dynamic_extended_capabilities     
* dynamic_offering_extension         
* multilingual_string_settings                 
* multilingual_string_settings_values
* offering_extension                    
* static_capabilities                
* time_settings             

Some examples of missing settings include:
* service.streaming.datasource (boolean)
* service.streaming.datasource.approach (boolean)
* rest.contentType.undefined (string)
* service.streaming.datasource.chunkSize (integer)

...and all EXI settings.

Do we intend to keep default_settings.sql updated in the future? If not, it should probably be deleted.

**Comment by shane-axiom** [comment]
@CarstenHollmann I forgot about this and it took a minute to figure out (that [default_settings.sql](https://github.com/52North/SOS/commits/develop/misc/db/default_settings.sql) isn't maintained and is missing many tables, settings, etc). Can we go ahead and delete it in favor of `default_settings.db`? The last meaningful commit to `default_settings.sql` was on [March 19, 2015](https://github.com/52North/SOS/commits/develop/misc/db/default_settings.sql).

**Comment by CarstenHollmann** [comment]
@shane-axiom I think we can delete both because the last commit to default_settings.db was on [17, 2014](https://github.com/52North/SOS/commits/develop/misc/conf/default_settings.db) and if no `configuration.db` is available in the deployed SOS, the SOS creates the `configuration.db` from the default settings.
