### ISSUE TITLE
ERROR log statements while importing observations: "Duplicity of the featureOfInterest identifier"

### ISSUE THREAD

**Issue by EHJ-52n** [52North/SOS#226]
I am receiving a lot of loggings of the following statement:
```
2015-05-18 12:41:48,867 ERROR [http-bio-127.0.0.1-8080-exec-4] [WritableCache.java:1501] Duplicity of the featureOfInterest identifier [...]
```

Version: 4.3.0-SNAPSHOT
Build date: 20150513-1637
Installation date: 2015-05-13 16:56:14

I use the SOS-Importer with import strategy "SweArrayObservationWithSplitExtension". 
The problem might be, that each InsertObservation request contains the feature of interest as instance and not reference.

The code in ```WritableCache.java```:
```java
    @Override
    public void addFeatureOfInterestIdentifierHumanReadableName(String identifier, String humanReadableName) {
        if (StringHelper.isNotEmpty(identifier) && StringHelper.isNotEmpty(humanReadableName)) {
            if (!getFeatureOfInterestIdentifierForHumanReadableName().containsKey(humanReadableName)) {
                getFeatureOfInterestIdentifierForHumanReadableName().put(humanReadableName, identifier);
            } else {
                LOG.error("Duplicity of the featureOfInterest identifier {}", identifier);
            }
        }
    }
```

Here, it should be checked, that the combination to add is already contained and not just the ```humanReadableName```.

**Comment by CarstenHollmann** [comment]
Fixed in pull request #235
