### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by autermann** [52North/SOS#233]
The license agreement link on the *Get Involved*  page results in a `404`:
http://52north.org/images/stories/52nadmin/files/52north%20contributor%20license%20agreement.pdf

**Comment by nuest** [comment]
the link should go to http://52north.org/about/licensing instead.

**Comment by autermann** [comment]
That link is already present, but there is a [direct link](https://github.com/52North/SOS/blob/master/spring/views/src/main/webapp/WEB-INF/views/get-involved.jsp#L50) to the pdf...

**Comment by nuest** [comment]
Then let's remove the direct linkt altogether, the other link will most likely be redirected if the homepage changes in the future.

**Comment by EHJ-52n** [comment]
Or replace it with http://52north.org/about/licensing/cla-guidelines. 

In addition, if you need a redirect of the broken link, just send a mail to our it-team. :wink:

**Comment by CarstenHollmann** [comment]
See #236
