### ISSUE TITLE
sml:position can not be decoded by SensorMLDecoderV20

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#247]
*I also sent this question to [52North swe forum](http://sensorweb.forum.52north.org/sml-position-can-not-be-decoded-by-SensorMLDecoderV20-tt4028079.html), but perhaps this is the appropriate place. Sorry for cross-posting.*

I'm trying to insert a sensor with JSON binding. I have added a position for the sensor:
```xml
<sml:position name="sensorPosition">
	<swe:Position referenceFrame="urn:ogc:def:crs:EPSG::4326">
		<swe:location>
			<swe:Vector gml:id="STATION_LOCATION">
				<swe:coordinate name="easting">
					<swe:Quantity axisID="x">
						<swe:uom code="degree"/>
						<swe:value>-1.597425</swe:value>
					</swe:Quantity>
				</swe:coordinate>
				<swe:coordinate name="northing">
					<swe:Quantity axisID="y">
						<swe:uom code="degree"/>
						<swe:value>42.81457</swe:value>
					</swe:Quantity>
				</swe:coordinate>
				<swe:coordinate name="altitude">
					<swe:Quantity axisID="z">
						<swe:uom code="m"/>
						<swe:value>17</swe:value>
					</swe:Quantity>
				</swe:coordinate>
			</swe:Vector>
		</swe:location>
	</swe:Position>
</sml:position>
```
I get the following error:
```json
{
	"version" : "1.1.0",
	"exceptions" : [{
			"code" : "NoApplicableCode",
			"text" : "sml:position can not be decoded by org.n52.sos.decode.SensorMLDecoderV20 because it is not yet implemented!"
		}
	]
}
```
The error is self-explanatory, but I would like to double check if I'm doing something wrong.

Is only JSON Binding affected or it breaks for all bindings? Is there any alternate way to add the location for the sensor? It is strange that the error returns "version": "1.1.0".

**Comment by CarstenHollmann** [comment]
Your sml:position definition looks like for SensorML 1.0.1. For SensorML 2.0 the sml:position definition should look like this (from the 52N SOS examples):

```xml
<sml:position>
	<swe:Vector referenceFrame="urn:ogc:def:crs:EPSG::4326">
		<swe:coordinate name="easting">
			<swe:Quantity axisID="x">
				<swe:uom code="degree" />
				<swe:value>7.651968812254194</swe:value>
			</swe:Quantity>
		</swe:coordinate>
		<swe:coordinate name="northing">
			<swe:Quantity axisID="y">
				<swe:uom code="degree" />
				<swe:value>51.935101100104916</swe:value>
			</swe:Quantity>
		</swe:coordinate>
		<swe:coordinate name="altitude">
			<swe:Quantity axisID="z">
				<swe:uom code="m" />
				<swe:value>52.0</swe:value>
			</swe:Quantity>
		</swe:coordinate>
	</swe:Vector>
</sml:position>
```

_"It is strange that the error returns "version": "1.1.0"."_

This is the version of the OWS Common specification where the exception is defined. In other words, it defines the exception version.

**Comment by jruizaranguren** [comment]
Thank you, it works like a charm. The sensor is inserted, although I still [can not recover the sensorml description through DescribeSensor](https://github.com/52North/SOS/issues/245).
