### ISSUE TITLE
NumericSettingDefinition breaks settings view in admin interface

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#255]
If you define a [NumericSettingDefinition ](https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/config/settings/NumericSettingDefinition.java) in a [SettingDefinitionProvider](https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/config/SettingDefinitionProvider.java), no settings are displayed during installation and in the admin interface.

The problem should be in the [application.js](https://github.com/52North/SOS/blob/master/spring/views/src/main/webapp/static/js/application.js).

Probably the NumericSettingDefinition was not used before and therefore, the problem has not yet occurred.

**Comment by autermann** [comment]
Yeah... [here](https://github.com/52North/SOS/blob/master/spring/views/src/main/webapp/static/js/application.js#L122) seems to be a `case` missing...
