### ISSUE TITLE
Environment parameter for settings import at startup

### ISSUE THREAD

**Issue by nuest** [52North/SOS#259]
Following up on the discussion on the mailing list: http://sensorweb.forum.52north.org/Automating-the-52N-SOS-install-td4028104.html

Wouldn't it be useful to have a startup parameter, e.g. `sos.configuration.import`, that has the same efferct as installing an SOS with the installation wizard and then importing a configuration that was previously exported?

**Comment by shane-axiom** [comment]
Is the aim to support both the configuration.db and datasource.properties?

One possibility would be to use environment variables to specify locations of `datasource.properties` and `settings.json` files to import, but only if `datasource.properties` and/or `configuration.db` didn't already exist in the installation.

Another option would be to support storing `datasource.properties`, `configuration.db`, and possibly Hibernate mappings externally from the webapp directory, and specifying the configuration path with an environment variable. This seems cleaner, but would require support for upgrading `configuration.db` databases when a newer version of the SOS is pointed to an old version of `configuration.db`.

**Comment by shane-axiom** [comment]
As I'm deploying new SOS instances and doing things like writing Dockerfiles for the SOS I really wish that the locations of `datasource.properties` and `configuration.db` could be stored outside of the webapp directory and specified by environment variables. I'm willing to implement this and make a pull request, any objections?

**Comment by CarstenHollmann** [comment]
That sounds great. So no objections from my size.
Maybe we can use this implementation to move the `datasource.properties` to the same folder as the `configuration.db`. Then both configuration files are in the same folder.

**Comment by nuest** [comment]
Hi Shane,

that would be a great solution. I've been working on some Dockerfiles for the 52N SOS as well - not to hard really. Looking forward to your feedback [1, 2].

The crucial thing for me is configurability, e.g. mounting `<host>/etc/sos.config` into the container so the SOS can pick that up, or copying the config files you mentioned into a container.

Also, Geonovum has some activities that I recently discovered: https://github.com/Geonovum/smartemission/blob/master/docker/sos52n/Dockerfile

[1] https://github.com/geocontainers/dockerfiles
[2] Images: https://hub.docker.com/r/geocontainers/52n-sos/ and https://hub.docker.com/r/geocontainers/52n-sos-alpine

**Comment by shane-axiom** [comment]
Sounds good, I'll work on this when I get a chance.

For reference, here's my Dockerfile for the i52n-sos project:

https://github.com/ioos/i52n-sos/blob/master/Dockerfile

**Comment by CarstenHollmann** [comment]
Supported in versions 4.4.x and 5.x
