### ISSUE TITLE
WaterML - invalid procedureDescriptionFormat

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#265]
Hi,

I'm currently learning how to use the SOS server with WaterML markup, and I have an error regarding the procedureDescriptionFormat.

Using the 52n-sensorweb-sos-bundle-4.3.0 (downloaded 20th June) the SOS server is running OK, and the test client JSON examples work.  I tried creating my own InsertSensor JSON as below.  I run this in the client request window, after running the example JSON InsertSensor() call using SOS 2.0.0.

    {
      "request": "InsertSensor",
      "service": "SOS",
      "version": "2.0.0",
      "procedureDescriptionFormat": "http://www.opengis.net/waterml/2.0/observationProcess",
      "procedureDescription": "<wml:WaterML xmlns:swes=\"http://www.opengis.net/swes/2.0\" xmlns:sos=\"http://www.opengis.net/sos/2.0\" xmlns:swe=\"http://www.opengis.net/swe/1.0.1\" xmlns:wml=\"http://www.opengis.net/waterml/2.0/observationProcess\" xmlns:gml=\"http://www.opengis.net/gml\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"1.0.1\"><wml:><wml:ObservationProcess gml:id=\"platform:1:sensor:1\"><wml:processType xlink:href=\"http://www.opengis.net/def/waterml/2.0/processType/Sensor\" xlink:title=\"Sensor\"/><wml:verticalDatum xlink:href=\"urn:ogc:def:crs:EPSG::4326\" xlink:title=\"Height datum\"/><wml:processReference xlink:href=\"http://www.labfacility.co.uk/pdf/thermocouple-resistance-thermometers-sensors-probes.pdf\" xlink:title=\"Labfacility PT100 External Temperature Sensor\"/><wml:input xlink:href=\"http://sweet.jpl.nasa.gov/2.3/propEnergy.owl#Heat\" xlink:title=\"Water Temperature\"/></wml:ObservationProcess></wml:></wml:WaterML>",
      "observableProperty": ["http://www.52north.org/test/observableProperty/1"],
      "observationType": ["http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement"],
      "featureOfInterestType": "http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/SF_SamplingCurve"
    } 

The reply from the server when running this in the test client gives:

    {
      "version" : "1.1.0",
      "exceptions" : [
        {
          "code" : "InvalidParameterValue",
          "locator" : "procedureDescriptionFormat",
          "text" : "The requested procedureDescriptionFormat is not supported!"
        }
      ]
    }

However, when I run getCapabilities() I see that it supports the waterml procedureDescriptionFormat

          "procedureDescriptionFormat" : {
            "allowedValues" : [
              "http://www.opengis.net/sensorML/1.0.1",
              "http://www.opengis.net/sensorml/2.0",
              "http://www.opengis.net/waterml/2.0/observationProcess"
            ]
          }

So, I'm not sure why it says the procedureDescriptionFormat value is not supported when the getCapabilities() function says that it is, as does the encoding tab in the admin section, and I'm also not sure why in the exception reply it uses version 1.1.0.

Any pointers on where I'm going wrong with this would be great,
David

**Comment by dbciar** [comment]
Also, I noticed on the wiki (link below) that it states only sensorml 1.0.1 and sensorml 2 are supported for insertSensor() and updateSensorDescription(), so I'm not sure which resource to follow.

https://wiki.52north.org/bin/view/SensorWeb/SensorObservationServiceIVDocumentation#Supported_ProcedureDescriptionFo

**Comment by CarstenHollmann** [comment]
WaterML 2.0 is not yet supported for the procedure description format in the InsertSensor operation. But you can insert a sesnor described in SensorML 1.0.1 and send a DescribeSensor request with WaterML 2.0 procedure description format for the sensor. In that case the SensorML 1.0.1 description is converted to WaterML 2.0.

The listing of WaterML 2.0 as procedure description format of the transactional operations in the Capabilities is not correct. We have created an issue #267 for that.

Supported procedureDescriptionFormat for insertion:
- SensorML 1.0.1 (http://www.opengis.net/sensorML/1.0.1)
- SensorML 2.0 (http://www.opengis.net/sensorml/2.0)

Supported procedureDescriptionFormat for requesting:
- SensorML 1.0.1 (http://www.opengis.net/sensorML/1.0.1)
- SensorML 2.0 (http://www.opengis.net/sensorml/2.0)
- WaterML 2.0 (http://www.opengis.net/waterml/2.0/observationProcess)

**Comment by dbciar** [comment]
Thanks, that's a fairly straight forward answer.  I'll get back to the SensorML schema for now.
