### ISSUE TITLE
SwesDecoderv20 and SwesStringDecoderv20 ambiguity

### ISSUE THREAD

**Issue by lestarcdog** [52North/SOS#270]
I have a reproducible error when I would like to enable my statistics module with the SOS 5.x.

Scenario 1. my module is disabled, it means I don't connect to the external Elasticsearch and I don't create a couple of prototype Spring beans. I specify my beans in the `configured-context.xml` .
1. I try to send a [InsertSensor request](https://gist.github.com/lestarcdog/a157af003df30a8f9745) from SoapUI.
2. [Error received](https://gist.github.com/lestarcdog/a81664308fe6d3329aa2)
3. Resend the initial request. Now it is working
   In the meantime it shows this debug message.
   `2015-07-09 16:32:21,028 DEBUG [http-apr-8080-exec-4] [AbstractCodingRepository.java:91] Requested ambiguous implementations for OperationDecoderKey[service=SOS, version=2.0.0, operation=InsertSensor, contentType=application/xml]: Found org.n52.sos.decode.SwesStringDecoderv20@700e23fd, org.n52.sos.decode.SwesDecoderv20@7ebd70b5; Choosing org.n52.sos.decode.SwesStringDecoderv20@700e23fd.`
4. The request is successfully processed.

Scenario 2. My statistics collection is enabled.
1. I try to send a [InsertSensor request](https://gist.github.com/lestarcdog/a157af003df30a8f9745) from SoapUI.
2. Same error received. [Error received](https://gist.github.com/lestarcdog/a81664308fe6d3329aa2)
3. Resend the InsertSensor request but I got this [error message](https://gist.github.com/lestarcdog/f652340532286ebdc42e).

Which is not surprising because
`2015-07-09 16:42:30,654 DEBUG [http-apr-8080-exec-2] [AbstractCodingRepository.java:91] Requested ambiguous implementations for OperationDecoderKey[service=SOS, version=2.0.0, operation=InsertSensor, contentType=application/xml]: Found org.n52.sos.decode.SwesDecoderv20@591c40fe, org.n52.sos.decode.SwesStringDecoderv20@42a73283; Choosing org.n52.sos.decode.SwesDecoderv20@591c40fe.`
 it chose the `SwesDecoderv20` instead of the `SwesStringDecoderv20` this time.

Is this an error on my side? 
There was a recent pull request about this Decoders https://github.com/52North/SOS/pull/253

**Comment by nuest** [comment]
First error received is ``Duplicate key org.n52.iceland.w3c.SchemaLocation@3ab5d546`` @autermann what do you think?

**Comment by lestarcdog** [comment]
The two bean are specified in [this context.xml](https://github.com/52North/SOS/blob/feature/5.x/coding/sos-v20/src/main/resources/configured-context.xml)

**Comment by autermann** [comment]
The first error is caused [here](https://github.com/52North/SOS/blob/feature/5.x/core/api/src/main/java/org/n52/sos/coding/encode/AbstractResponseEncoder.java#L226). `Collectors.toMap()` fails, as there is are to `SchemaLocation`s with the same namespace. We should a merger function to that call...


Regarding the decoder choosing. They have the very same key (namely `XmlDecoderKey("SOS", "2.0.0", "InsertSensor")`, so both may be chosen...

@CarstenHollmann what's `SwesStringDecoderv20` for?

**Comment by CarstenHollmann** [comment]
The ...StringDecoder... is required for the Iceland bindings to avoid XmlBeans.

**Comment by CarstenHollmann** [comment]
See #293
