### ISSUE TITLE
Add JSON GetObservation example with MergeObservationsIntoDataArray extension

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#276]
Add JSON GetObservation example with MergeObservationsIntoDataArray extension like this:

```
"extensions": [
    {
        "definition": "MergeObservationsIntoDataArray",
        "value": true
    }
]
```

https://wiki.52north.org/bin/view/SensorWeb/SensorObservationServiceIVDocumentation#MergeObservationsIntoDataArray

**Comment by rafacuest** [comment]
Very useful

**Comment by CarstenHollmann** [comment]
Add in https://github.com/52North/SOS/commit/d9d0e5c4d5b9518cba8547f7f7b55df0a6dc3c5f#diff-f212a7e907f1a65ea5b356411f8ace78
