### ISSUE TITLE
Extend the supported coordinate names

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#279]
Add support for further coordinate names, perhaps through settings.

**Comment by EHJ-52n** [comment]
And you should add some better error message here:

https://github.com/52North/SOS/blob/develop/converter/transformation/coordinate/src/main/java/org/n52/sos/converter/CoordianteTransformator.java#L506

Something like: The given coordinate name coordinate.getName() is not supported. Supported names are SweCoordinateName.getAllNames()!
