### ISSUE TITLE
Exception or return single observations if GetObservation contains merge flag and observations are OM_SweArrayObservations

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#280]
If the user requests observations with the merge observation flag in the GetObservation request and the queried observations are OM_SweArrayObservation the SOS returns an empty response beacuse the merging of OM_SweArrayObservation is not yet supported.
Solutions:
1) Throw an exception
2) Return single OM_SweArrayObservation

**Comment by autermann** [comment]
Closed by #302
