### ISSUE TITLE
SOS 5.x w/ and w/o Statistics module

### ISSUE THREAD

**Issue by lestarcdog** [52North/SOS#293]
Somehow the SOAP, POX and KVP encodings doesn't generate a response for the requests. It gives most of the time Springframework's NoSuchBeanDefinitionException Exceptions but a Iceland [duplicate schema location key is also common common](https://gist.github.com/lestarcdog/b196dddaa8c6a38a48b9). Can you give me some hint why could this happen? I posted the whole debug traces for the requests.

**SOAP and KVP DescribeSensor**
[Error gist](https://gist.github.com/lestarcdog/8542cfa12de1f94ed18f)

**JSON GetCapabilities**
[Error gist](https://gist.github.com/lestarcdog/bb6c2aa58c601a800a35)

**POX DescribeSensor**
[Error gist v100](https://gist.github.com/lestarcdog/fed61d6a1879336dfc97)
[Error gist v200](https://gist.github.com/lestarcdog/b7d790e114a439211f0d)
this one is maybe connected to this issue #270

**Comment by nuest** [comment]
This is a blocker for the demonstration of the statistics features, because only JSON requests work.

**Comment by autermann** [comment]
Regarding the schema location problem, see my comment in #270.

```
java.lang.ClassCastException:
  java.lang.String cannot be cast to org.apache.xmlbeans.XmlObject
```
Also related to #270. The wrong decoder is chosen as the string decoders have the same keys...

@CarstenHollmann  We have to introduce new keys for that...

```
java.io.IOException:
  org.n52.iceland.exception.ows.concrete.NoEncoderForKeyException:
    Could not find encoder for key 'JSONEncoderKey{type=class org.n52.iceland.ogc.gml.time.TimePeriod}'
```
Looks like the `json-common` module is missing the bean definitions for the encoders in `org.n52.sos.encode.json.base`...


```
org.springframework.beans.factory.NoSuchBeanDefinitionException: 
  No qualifying bean of type [org.apache.xmlbeans.XmlOptions] found for dependency:
    expected at least 1 bean which qualifies as autowire candidate for this dependency.
```
Just a guess, but I think [this](https://github.com/52North/SOS/blob/feature/5.x/core/api/src/main/java/org/n52/sos/coding/encode/AbstractXmlEncoder.java#L52) should be a `Producer` and not a `Provider`...

**Comment by CarstenHollmann** [comment]
New key for XML string decoder was introduced in https://github.com/52North/SOS/commit/c6870d721ef21310499e2945be597e5848c86960.
The issue should be fixed with this.
