### ISSUE TITLE
SimpleProcess can not be decoded

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#307]
I'm getting the following error message when inserting sensors with JSON binding: 

*SimpleProcess can not be decoded by org.n52.sos.decode.SensorMLDecoderV20 because it is not yet implemented* 

It seems that simple processes are considered in the SensorMLDecoderV20 class. Is this a problem exclusive of JSON binding or it is just a feature to be done?

**Comment by CarstenHollmann** [comment]
I was able to insert a SimpleProcess with a build from the current develop branch.

If a request throws an exception it is always helpful to provide the failing request.

**Comment by jruizaranguren** [comment]
I will try again with the develop branch. I tested it with v4.3.2.
