### ISSUE TITLE
Invalid feature of interest type

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#308]
I was planning to use our own taxonomy for feature of interest type, but when I insert a sensor with an arbitrary name (such as http://path.to/sim/chlorinedecay) I'm getting an InvalidParameterValue exception.

Which are valid feature of interest types (in addition to OGC-OM/2.0/ types)? Is there a mechanism to use custom vocabularies?

**Comment by CarstenHollmann** [comment]
*Which are valid feature of interest types (in addition to OGC-OM/2.0/ types)?*
- Currently, only the OGC-OM/2.0/ featureOfInterest types are supported.

*Is there a mechanism to use custom vocabularies?*
-  Extend the SOS with your own feature decoder/encoder for your featureOfInterest type.

**Comment by jruizaranguren** [comment]
Thanks.
