### ISSUE TITLE
Components of AggregateProcess are not considered procedures

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#309]
I have tried to insert an example of an [AggregateProcess with components defined inline](http://www.sensorml.com/sensorML-2.0/examples/aggregate.html). I have defined each component as a PhysicalComponent instead of SimpleProcess due [other existing issue](https://github.com/52North/SOS/issues/307).

Each component is correctly defined and identified procedure, with its own inputs, outputs, location and related feature of interest within the AggregateProcess. Each component produces observations, no matter how the AggregateProcess uses these observations to create further calculations.

I would expect to be able to query each of the observations produced by these components when inserting aggregate processes. In the [sensorweb forum, it is suggested to use the hierarchicalProcess extension](http://sensorweb.forum.52north.org/Insufficient-error-description-when-encoding-SensorML-tt4028152.html) to allow this linkage. Although this is a solution for my current needs, it seems that AggregateProcess could be used to this extent without the need of an extension.

**Comment by CarstenHollmann** [comment]
The SOS does not insert the components as separate procedures into the database for which you can insert or query observations, see issue #273.

If you want to insert and query observations produced by the components you have to insert them as separate procedures into the SOS with linkage (`attachedTo` in SensorML 2.0) to the AggregatedProcess.

**Comment by jruizaranguren** [comment]
Thanks. I will add the suggestion as a comment on issue #273.
