### ISSUE TITLE
Improve log output of transactional security implementation

### ISSUE THREAD

**Issue by EHJ-52n** [52North/SOS#31]
The current output of the transactional security implementation:

```
2014-04-04 14:11:05,100 WARN [http-bio-8080-exec-38] [ExceptionLogger.java:73] Exception thrown
org.n52.sos.exception.ows.NoApplicableCodeException: Not authorized for transactional operations!
[... removed long stacktrace]
```

could be improved to contain the source in terms of IP or hostname that was blocked. From my point of view, the exception stack trace should not be logged each time on level WARN but maybe something like DEBUG.

**Comment by gamesbook** [comment]
Is this going to be tackled?  I just "hit" the same issue on a new install.  It would be even better if the error was followed by a suggestion, e.g.:
```
Update your xyz configuration file by ...
```

**Comment by EHJ-52n** [comment]
Good point.

As the SOS is not using a configuration file for this, we should provide a link to the configuration setting in the administrator web interface:
``` http://sos-host.example.com/52n-sos-webapp/admin/settings#transactional_security ```

**Comment by gamesbook** [comment]
That is what I found I had to do.  It did not work... not sure what I doing wrong.

**Comment by EHJ-52n** [comment]
If you are using IPv6 you might have hit 52North/iceland/issues/20.

**Comment by lukejpreston** [comment]
I am having the same issue is there any progress on this?

Also, it would be great if it could do hostname and not just ip address

**Comment by CarstenHollmann** [comment]
See https://github.com/52North/arctic-sea/issues/14
