### ISSUE TITLE
GetCapabilitiesRequest with POX-binding loses the version tag

### ISSUE THREAD

**Issue by ahuarte47** [52North/SOS#328]
There is a weird behavior for GetCapabilitiesRequest class using POX-binding. The 'isSetAcceptVersions' property is true and then the version is not assigned similar for requests from JSON-binding (The 'isSetAcceptVersions' property is false).

https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/request/GetCapabilitiesRequest.java#L85

Here I propose a fix:

```
@Override
public List<ServiceOperatorKey> getServiceOperatorKeyType() {
    if (serviceOperatorKeyTypes == null) {
        if (isSetAcceptVersions()) {
            serviceOperatorKeyTypes = new ArrayList<ServiceOperatorKey>(acceptVersions.size());
            for (String acceptVersion : acceptVersions) {
                serviceOperatorKeyTypes.add(new ServiceOperatorKey(getService(), acceptVersion));
            }
# -----> #  if (getVersion() == null) {
# -----> #      setVersion(Collections.max(acceptVersions));
# -----> #  }
        } else {
            Set<String> supportedVersions =
                    ServiceOperatorRepository.getInstance().getSupportedVersions(getService());
            if (CollectionHelper.isNotEmpty(supportedVersions)) {
                setVersion(Collections.max(supportedVersions));
            }
            serviceOperatorKeyTypes =
                    Collections.singletonList(new ServiceOperatorKey(getService(), getVersion()));
        }
    }
    return Collections.unmodifiableList(serviceOperatorKeyTypes);
}
```

Best Regards 
Alvaro

**Comment by CarstenHollmann** [comment]
In the specification the GetCapabilities request does not have a version and at this point we do not know which version from acceptVersions is supported by the SOS.

**Comment by ahuarte47** [comment]
Ok, thanks for your reply. This question came from a request class is created from a GetCapabilitiesRequest with POX-binding. 

See:
https://github.com/52North/SOS/blob/master/core/api/src/main/java/org/n52/sos/request/operator/AbstractRequestOperator.java#L163

In this case the version tag is null, but it is assigned when the request is created from a GetCapabilitiesRequest with JSON-binding. 

I have problems with this behavior. I am writing a plugin for this software and I need check the requested version now only present in the related response class.

**Comment by nuest** [comment]
Why do you not check the acceptVersions parameter?

**Comment by ahuarte47** [comment]
Ok, I can check it when the version tag is null. I only wanted report this behavior.
Thanks!
