### ISSUE TITLE
Duplicated alter table commands in PG_series_script_create.sql

### ISSUE THREAD

**Issue by ahuarte47** [52North/SOS#336]
Hi, the "PG_series_script_create" sql script from develop branch (it creates the postgreSQL's database schema) has several duplicate entries.

See:
https://github.com/52North/SOS/blob/develop/misc/db/PostgreSQL/series/PG_series_script_create.sql#L312

It throws error when is executed.

Best Regards.
Alvaro

**Comment by ahuarte47** [comment]
Hi, I see same issue in other scripts

**Comment by CarstenHollmann** [comment]
The provided SQL scripts of the develop branch are an addition and not required for the installation of the 52°North SOS. The database schema can be created via the 52°North SOS installation wizard which is the recommended procedure.

The provided SQL scipts were created with the [SQLScriptGenerator](https://github.com/52North/SOS/blob/develop/hibernate/mappings/src/main/java/org/n52/sos/SQLScriptGenerator.java)

In previous versions of this class, the duplicity of statements was not checked. In the current version the duplicated statements are removed but the provided SQL scripts were probably not yet updated.

**Comment by ahuarte47** [comment]
OK, thanks for reply. I will use your advice.
