### ISSUE TITLE
Procedure's hibernate mapping file wrong?

### ISSUE THREAD

**Issue by ahuarte47** [52North/SOS#337]
Hi, I execute a "GetObservation" request using the current "develop" branch, and It throws an error when the request contains a procedure tag,

For example in JSON:
{
  "request": "GetObservation",
  "service": "SOS",
  "version": "2.0.0",
  "procedure": "procedure:MCP_SCADA_CL/ASTAD1CL01.VP"
}

The sql statement throws:
"ERROR:  procedure3_.typeof field not exist.
LINE 1: ..._2_, procedure3_.referenceFlag as referen12_0_2_, procedure3..."

The Procedure's hibernate mapping file has the "typeOf" tag:
https://github.com/52North/SOS/blob/develop/hibernate/mappings/src/main/resources/mapping/core/Procedure.hbm.xml#L102

But the database table in postgis hasn't the field "typeof"

It is a bug?

Best Regards
Alvaro

**Comment by CarstenHollmann** [comment]
The mapping files are correct and if you create the tables during the installation process of the 52°North SOS, the valid database schema will be created.

If you use the provided SQL scripts, then keep in mind that they are not always up to date in the develop branch.

Therefore, we recommend to use the installation wizard of the 52°North SOS to create the database schema.

**Comment by ahuarte47** [comment]
OK, thanks for reply. I will use your advice.
