### ISSUE TITLE
How to make work flexible identifiers

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#344]
I would like to provide flexible identifiers for procedure, feature of interest and observable properties.
I'm using version 4.4.0.Snapshot before build was broken.

I have activated in the configuration all conversion of flexible identifiers as the documentation suggests.

I have added a `gml:name` element after `gml:identifier` for the procedure, but in the response I get back the identifiers as well as within the capabilities document. The example:

```
<gml:identifier codeSpace="uniqueID"> http://idena.navarra.es/olk/ad1/cl01</gml:identifier>
<gml:name>chlorinemeter cl01 of ad1 in olk</gml:name>
```

I have tried this in POX and JSON bindings with no success. Do I need to make any additional step?
I also tried to fullfil the name field in relatedFeature (for the JSON binding) to see If I was able to get a human-friendly name for the feature of interest. But, again, no success.

How should I proceed to have process, feature of interest and observable property flexible identifiers?

Thanks.

**Comment by CarstenHollmann** [comment]
If you insert an encoded featureOfInterest with `gml:name`, the name is stored in the database. If you enable the flexibleIdentifier, the name should be used as identifier in the response.

For observableProperty and procedure the transactional insertion of the name (`gml:name`) is not yet supported. In this case you have to add the values directly in the related database tables.

**Comment by jruizaranguren** [comment]
Ok, the documentation and the admin panel can mislead other users also, because it appears that offering, procedure, observable property and feature of interest can have flexible identifiers.

**Comment by dbciar** [comment]
Hi jruizaranguren,

There are a couple of things that might help in the mean time (I think - I'm a user like you so take this as not 100% sure), if you really need the functionality you can update the database yourself.  

For example, when I use InsertSensor, I set the SOS swes:ObservableProperty elements as URL links to ontologies, however this means that in the JS-Client the URL is shown as the category/phenomena, this is not so user friendly.  By going to the the observableproperty table in the database, I can set the name column value for the different observable properties, which is then used in the JS-Client.

Also I found that using the name element of a feature of interest in a GetFeatureOfInterest call worked for me using both JSON and POX encoding (SOS server bundle 4.3.4) with a caveat.  I created a ResultTemplate which included the following foi description:

https://gist.github.com/dbciar/0358fe8a25070f24add2

When I tried to use GetFeatureOfInterest with either the name or unique ID, I got an error back informing me the unique ID was invalid.  However, once I had added results to the system, both JSON and POX calls to GetFeatureOfInterest using the name or unique ID element values worked, e.g.:

{
  "request": "GetFeatureOfInterest",
  "service": "SOS",
  "version": "2.0.0",
  "featureOfInterest": "Loch Awe"
}

**Comment by CarstenHollmann** [comment]
Transactional insertion of name for procedure and obsevedProperty is now supported since #415
