### ISSUE TITLE
Development Branch always 'enriching with discovery information'

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#351]
Hello,

I compiled the develop branch as it was on the 4th November (I can see no commits between then and now), and I've been examining the output of DescribeSensor for InsertedProcedure's.  I cannot stop the SOS Server from inserting 'short name' and 'long name', using SOS 2.0, SML 2.0, POX for insert/describe SOS calls.

In the 'Procedure Description Enrichment' tab of the settings, I have unchecked every check box and saved the settings.  

I then insert a PhysicalSystem, first the example 'type', and then the example 'instance' of the hydrophone PhysicalSystem.  Now executing a DescribeSensor for the instance with procedure ID 'ExampleHydrophone1', I can see the server has added a long name and a short name identifier - I assume because the definition for these identifiers in the InsertSensor example have the nexos dictionary URI, and not the 'urn:ogc:def:identifier:OGC:1.0:....' based definitions in the settings.

I assume that this shouldn't happen if the "Enrich with discovery information?" checkbox is not checked.

**Comment by CarstenHollmann** [comment]
This is an issue in the check method whether the long and short name should be added.
