### ISSUE TITLE
validTime in DescribeSensor, and after UpdateSensorDescription

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#360]
Hello,

I was attempting to enter a number of different procedure descriptions for the same procedure, all with different validTime TimePeriod values, none temporally overlapping, and with different gml:id attribute values for validTime.  

When I called DescribeSensor after inserting the procedure, the validTime at the root of the swes:sensorDescription element did not reflect the validTime I had entered.  Then I tried to updateSensorDescription with a second validTime, and when I called DescribeSensor, there was only one swes:sensorDescription element when I was expecting two, one for each validTime element entered, and it had the same TimePeriod values as the first time I called DescribeSensor.  

My reading of section 7.2.2.6 of the SensorML schema document led me to believe this may not be the expected behaviour.

For example, using the current development branch, SOS 2.0, SML 2.0, POX binding, and modifying the Client InsertSensor example 'Insert sensor - with SensorML 2.0 description (SOS 2.0.0)' to first have the validTime element of:
```
  <sml:validTime>
    <gml:TimePeriod gml:id="first_deployment">
      <gml:beginPosition>2011-01-01T00:00:00.000Z</gml:beginPosition>
      <gml:endPosition>2012-01-01T00:00:00.000Z</gml:endPosition>
    </gml:TimePeriod>
  </sml:validTime>
```
Followed by a call to updateSensorDescription and modify the validTime to the following:
```
  <sml:validTime>
    <gml:TimePeriod gml:id="second_deployment">
      <gml:beginPosition>2013-01-01T00:00:00.000Z</gml:beginPosition>
      <gml:endPosition>2014-01-01T00:00:00.000Z</gml:endPosition>
    </gml:TimePeriod>
  </sml:validTime>
```
Now when I call DescribeSensor for the procedure (http://www.52north.org/test/procedure/9) before and after the UpdateSensorDescription, there is only one swes:sensorDescription element, which shows the same validTime both times, shown below:
```
  <swes:description>
    <swes:SensorDescription>
      <swes:validTime>
        <gml:TimePeriod gml:id="tp_90CF44606F4B063324459FECC52413326BC88C86">
          <gml:beginPosition>2015-11-09T14:16:01.874Z</gml:beginPosition>
          <gml:endPosition indeterminatePosition="unknown"/>
        </gml:TimePeriod>
      </swes:validTime>
      <swes:data>
```
I tried checking with GetCapabilities to see if details of conformance class identifiers were in those results, as I wanted to check if it was documented whether the swe sensorHistoryProvider/Manager conformance classes were supported before posting here, but I couldn't see any list of that sort.

Best,
David

**Comment by dbciar** [comment]
I just found the following on the wiki:

##
 How can you create sensor descriptions for a specific period of time?

The SWE service model defines quite complex rules how to handle sensor description updates with respect to the validTime contained in the updated sensor descriptions (see requirements 38 to 42). For the sake of simplicity we implemented only the behaviour of requirement 43 so far: if a sensor description is updated at point in time t1 then the validTime interval of the existing sensor description is updated to end at t1, and the new sensor description is valid from t1 on.

If an update sensor operation does contain a validTime element then the service currently throws and exception. 
##

I did read the wiki what seems a long time ago - I had forgotten/missed this.  Though going by the above - I don't get an error when the update sensor description operation contains a validTime element.

**Comment by CarstenHollmann** [comment]
I have checked this and if I add a `swes:validTime` element to the `swes:SensorDescription` like this:
```
<swes:validTime>
    <gml:TimePeriod gml:id="validTime">
        <gml:beginPosition>2013-08-14T15:02:43.219</gml:beginPosition>
        <gml:endPosition>2013-08-14T15:02:47</gml:endPosition>
    </gml:TimePeriod>
</swes:validTime>
```
The SOS throws an exception that this is not yet supported.

**Comment by dbciar** [comment]
Sorry - when you say adding it to the swes:SensorDescription, do you mean under the inherited DescribedObject elements of a sensor, so the validTime element in Figure 7.8 of the SensorML 2.0 12-000 document, between classification and securityConstraints?

I didn't use `<swes:validTime>` as in the SensorML 12-000 document the example use of it uses `<sml:validTime>` (using a quick ctrl+f) - I thought the validTime element was in the same sml namespace as all the other DescribedObject inherited elements?

**Comment by CarstenHollmann** [comment]
The `<swes:validTime>` is defined in  [OGC SWE Service Model 09-001](http://www.opengeospatial.org/standards/swes) and this validTime element is considered by the SOS.
The validTime in the SensorML is not considered because a sensor description need not be in SensorML.

**Comment by dbciar** [comment]
Ah found it: section 9.2.3, table 21.  And I see your point about the sensor description not necessarily being in SensorML.  Conversely I can see why it would want to be included in the sensorML description as well as in the service call to the SOS server.

Thanks for the help, I was looking at this in the wrong way.
