### ISSUE TITLE
typeOf xlink:href not automatically populated for inline defined components

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#364]
Hello,

After the following discussion,

http://sensorweb.forum.52north.org/Basic-inheritance-using-typeOf-property-td4028231.html

I've been using the develop branch of the software, and successfully using typeOf element by setting the xlink:title attribute to the procedure ID, and having the SOS server populate the xlink:href with the KVP value.  However I was creating a PhysicalSystem with multiple components defined inline, using the typeOf element to reference the 'base' sensor for these inline components.  When used for inline components the xlink:href is set to 'UNKNOWN'.

For example if you add the following components element to a procedure definition, having already entered the example 'http://www.52north.org/test/procedure/9' from the test client,

```
    <sml:components>
        <sml:ComponentList>
            <sml:component name="prt_one">
                <sml:PhysicalComponent gml:id="prt_one_component" 
                        definition="ontology/link/to/definition">
                    <gml:description>A PRT sensor as part of a PRT chain in position one depth 1m</gml:description>
                    <gml:identifier codeSpace="uniqueID">/unique/procedure/id/here</gml:identifier>
                    <gml:name>PRT Chain sensor 1</gml:name>

                    <sml:typeOf xlink:title="http://www.52north.org/test/procedure/9"/>
                    <sml:configuration>     
                        <sml:Settings>
                            <sml:setValue ref="parameters/Depth">1</sml:setValue>
                        </sml:Settings>
                    </sml:configuration>
                </sml:PhysicalComponent>
            </sml:component>
        </sml:ComponentList>
    </sml:components>
```
then the output following a describe sensor request shows the following for the inline component:
```
<sml:typeOf xlink:href="UNKNOWN" xlink:title="http://www.52north.org/test/procedure/9"/>
```
I have checked to make sure I was using the typeOf correctly, by using it outwith an inline element and it worked fine.  Using the develop branch compiled this afternoon, SML 2.0, SOS 2.0, POX binding.

**Comment by CarstenHollmann** [comment]
The SOS does not yet supported to insert components of a System/PhysicalSystem as separate procedures, see https://github.com/52North/SOS/issues/273.
Therefore, the `component` does not exist in the SOS as a procedure and there is no relation between the `component` and `typeOf` procedure of the component in the database. Since the SOS does not know the link, no  `xlink:href` with the KVP DescribeSensor request is created in the `component`.

**Comment by dbciar** [comment]
Ah I see.  I was aware that the inline components were not added as separate procedures, but because the SOS server added the `xlink:href='UNKNOWN'` attribute, I thought that there was functionality to add that information, and it was getting confused between identifying the need to add a href, and adding the correct href.  I'll add the KVP manually for documentation then.

Thanks.
