### ISSUE TITLE
InsertResult adding result to every observation offering available

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#397]
Hello,

I've been using the current development branch, 293886d813bf9d5d4e611136ee33149fb288a9a8, with SOS 2.0.0, POX encoding.  I've found that if I have defined a procedure with more than one observation offering, and I add observations using InsertResult, via a registered template with a single observation offering, the software inserts the observations under every observation offering related to the procedure.  If however I use InsertObservation, only the specified observation offering is used.

With the examples found in the client, use the InsertSensor 'with SensorML 2.0 description' example, but insert it three times, with a different observation offering each time, say 'raw', 'hourly', 'daily'.  Next, use the 'InsertResultTemplate (SOS 2.0.0)' for the example InsertSensor procedure added previously, with the observation offering set to 'raw'.  Now use the example InsertResult with this template.  Checking the database shows that the table observationhasoffering has records for the inserted observations against all three observation offerings, and not just 'raw'.

I checked the SOS specification (OGC 12-006, section 11.11.1) to make sure I was correct in my understanding of InsertResult/Template, and I thought this looks like a bug.

**Comment by danben-72** [comment]
I have confirmed this occurence with the current development branch.

**Comment by filfreire** [comment]
I can also confirm this behavior/bug.
