### ISSUE TITLE
Duplicate foreign key in observableproperty database table

### ISSUE THREAD

**Issue by matthias-mueller** [52North/SOS#406]
In the `observableproperty` database table, the foreign keys for `codespace` and `codespacename` point to the same foreign key `` (observed with SOS version 4.3.6). SQL definition is:

```
CREATE TABLE observableproperty
(
...
codespace bigint --Relation/foreign key to the codespace table. Contains the gml:identifier codespace
codespacename bigint --Relation/foreign key to the codespace table. Contains the gml:name codespace
...
CONSTRAINT obspropcodespaceidentifierfk FOREIGN KEY (codespace)
    REFERENCES codespace (codespaceid) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT obspropcodespacenamefk FOREIGN KEY (codespacename)
    REFERENCES codespace (codespaceid) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
...
)
```

One of them could/should be removed, I guess.

**Comment by CarstenHollmann** [comment]
This is correct. The foreign keys for `codespace` and `codespacename` point to the same table but can have different values.

**Comment by matthias-mueller** [comment]
This does not make sense to me. The referenced table ```codespace``` has only two columns:
```codespaceid(bigint) | codespace(varchar)```. Each row defines a single codespace.
Example:
```
3;"http://www.opengis.net/def/nil/OGC/0/unknown"
4;"http://aurora.regenstrief.org/UCUM"
```
Why should somebody use the value of (3) for ```codespace``` and the value of (4) for the ```codespacename```?

**Comment by CarstenHollmann** [comment]
The codespace is the `codespace` for the `identifier` (`gml:identifier`) and the `codespacename` is the codespace for the `name` (`gml:name`). Both GML elements have a codeSpace which may be different. The `codespacename` can be left blank because the codespace for the name is not required.

The `observableproperty` has also the  `codespace` and the `codespacename` columns to have the same base structure of the tables for the main SOS objects `Procedure`, `ObservableProperty, `FeatureOfInterest` and `Offering`.

**Comment by matthias-mueller** [comment]
Thats was clear, thanks. Could be helpful to add this information to the documentation of the [database model](https://wiki.52north.org/bin/view/SensorWeb/SensorObservationServiceDatabaseModel#Core_database_model).

**Comment by CarstenHollmann** [comment]
I have added these information to the [database model description](https://wiki.52north.org/bin/view/SensorWeb/SensorObservationServiceDatabaseModel#codespace_and_codespacename_colu).
