### ISSUE TITLE
Failed conversion between SML 2.0 and SML 1.0.1

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#422]
Hello,

The following is using the released version of the SOS (4.3.6), downloaded from 52north.org in the bundle download (created timestamp of: 2015-12-14 14:45:26), and using SOS 2.0, POX, SML 2.0.

So, using the "InsertSensor -> Insert Sensor with SensorML 2.0 Description" client example, the sensor definition is inserted OK, and a subsequent DescribeSensor request using SensorML 1.0.1 procedureDescriptionFormat works OK.

Performing the same as above, but this time changing the sensor definition from a PhysicalSystem to a PhysicalComponent, the subsequent DescribeSensor request using 1.0.1 procedureDescriptionFormat returns a 200 HTTP value, but with an empty contents.

Checking the GetCapabilities after inserting the client sensor example as a PhysicalComponent it does list SensorML 1.0.1 as an allowed procedureDescriptionFormat, and so this seems to either be a bug, or the GetCapabilities is reporting the wrong procedureDescriptionFormat.

David

**Comment by CarstenHollmann** [comment]
Hi David,

the encoding of SensorML 1.0.1 _Component_ (SenosrML 2.0 PhysicalComponent) is not supported in the SOS 4.3.x. But the encoding of the SensorML 1.0.1 _Component_ is implemented in the develop branch (4.4.x), see the commit [Add encoding support for SML 1.0.1 Component ](https://github.com/52North/SOS/commit/569b84630898fd3c75a6b77e42ad3c200fed06d9).
