### ISSUE TITLE
sensor description outputs are overwritten 

### ISSUE THREAD

**Issue by sanguinela** [52North/SOS#432]
How I have written here with more details (http://sensorweb.forum.52north.org/sensorDirectory-amp-descriptionfile-column-td4028518.html) , if I add some elements in sensorML of sensor like <swe:constraint> NilValue and so on, I have some problems.  If I am lucky the addition of these elements is supported and in this case , when I call getDescribe operation, in output this elements are deleted.

**Comment by CarstenHollmann** [comment]
Hi @sanguinela,

Thanks for creating this issue.

We have fixed this issue in this pull request https://github.com/52North/SOS/pull/431.

Please check out the current version from GitHub [(develop](https://github.com/52North/SOS/commits/develop) branch (4.4.x) or [4.3.x maintenance](https://github.com/52North/SOS/tree/maintenance/4.3) branch)

**Comment by sanguinela** [comment]
Hi Carsten, I compiled develop branch 4.4.0. It seem now it's all ok. 
Thank so much

**Comment by CarstenHollmann** [comment]
Fixed by #431

**Comment by sanguinela** [comment]
Sorry Carsten, I found another problem. In the same way, it seem that in sensorML is not supported CONTACTS, HISTORY and DOCUMENTATIONS elments? It's right? It's a problem or is an expected behavior?

**Comment by CarstenHollmann** [comment]
Hi @sanguinela,

I will check this but it looks like the same issue.

**Comment by CarstenHollmann** [comment]
Hi @sanguinela,

_History_ is not supported therefore this elements are not affected.
_Contacts_ and _Dokumentations_ are supported and I have checked the encoding of these elements. With the pull request #433 the elements are now only added if no element exists in the XML description.
