### ISSUE TITLE
PostgreSQL: defaultval('..._seq') as default values vor id-columns

### ISSUE THREAD

**Issue by DS-NV** [52North/SOS#465]
Dear 52north-Team,

with the current 52n-sensorweb-sos-bundle (4.3.7, [1]), using a PostgreSQL-database, there are 19 sequences for observationid and other ids. However, the default value for observationid (and the other corresponding ids) in observation table is NULL instead of nextval('observationid_seq').

I wonder if you have a particular reason to do so and if not, if you want to set these default values in future releases. I use such a default value vor observationid when I bulk import lots of entries in the observation table with the COPY-Implementation of python's psycopg2. With nextval(...) as default value, I can ommit the observationid column during the bulk import, which saves some processing time. Of course, anybody can manually add the default values, I was just wondering.

Best wishes
Daniel

[1] [http://52north.org/downloads/download/3-sos/490-52n-sensorweb-sos-4-3-7](http://52north.org/downloads/download/3-sos/490-52n-sensorweb-sos-4-3-7)

**Comment by CarstenHollmann** [comment]
Hi Daniel,

the database schema is created by the Hibernate framwork and the default use case to insert data into the SOS is to use the transactional operations. In this case Hibernate ensures that the next ID value is retrieved from the sequence.

Best,
Carsten

**Comment by DS-NV** [comment]
Hi Carsten,

thanks for the Explanation!

Best wishes
Daniel
