### ISSUE TITLE
missing EPSGs after maven clean install

### ISSUE THREAD

**Issue by MOSapeizer** [52North/SOS#476]
After maven clean install,
it will throw EPSG 4326 is not supported when insert observations.

there is my cache summary,  I found there is no built-in EPSGs in SOS

> default_epsg 4326
> global_envelope         SosEnvelope[envelope=null, srid=4326]
> last_update                 2016-10-04T23:09:44.338+08:00
> max_phenomenon_time null
> max_result_time         null
> min_phenomenon_time null
> min_result_time         null
> num_epsgs                   0
> num_feature_of_interest_types     7
> num_features_of_interest          0
> num_observable_properties         1
> num_observation_types   10
> num_offerings   281
> num_procedures  281
> num_related_features    0
> num_result_templates    0

**Comment by CarstenHollmann** [comment]
Which version of the 52N SOS do you use?

Did you see "settings" on the settings configuration page during the
installation process?
Sometimes the browser (so far mainly with Firefox) does not show the
settings which means that the settings in the SOS are not set.

You can re-run the installation process by resetting the SOS via the
admin interface (Admin -> Reset). If the settings are not displayed on
the configuration page normally a refresh of the browser will help.
