### ISSUE TITLE
Add default="NULL" to nullable timestamp properties in mapping files

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#490]
In MySQL the default behavior for timestamp columns is to set the current date/time instead of null 
Which leads to unexpected behavior in the SOS. 
To avoid this, the nullable timestamp properties should be defined wiht default="NULL".

**Comment by sounak98** [comment]
I'll take it up.

**Comment by CarstenHollmann** [comment]
Fixed by 52e75dc4719318c01fa06ecc6248ffb6352b9177
