### ISSUE TITLE
DeleteObservation of singleton observation throws NullPointerException 

### ISSUE THREAD

**Issue by tslawecki** [52North/SOS#498]
The DeleteObservation request threw a NullPointerException for an example test case I created with a single observation in the associated observationseries, so there may be an edge case not fully addressed in the implementation.

As an aside,the DeleteObservation request added by 52 North as an extension to the SOS standard is of high value to the US EPA project I've been working on. Data partners sometimes identified errors in their data after posting, and DeleteObservation supports the replacement of erroneous data.

**Comment by CarstenHollmann** [comment]
I have tested this with the current development branch and the DeleteObservaiton operation works for a single observation. No NullPointerException is thrown.
