### ISSUE TITLE
observation.identifier value not set when using InsertResult

### ISSUE THREAD

**Issue by tslawecki** [52North/SOS#499]
Use of InsertResult and DeleteObservation are not currently compatible in 52N SOS, as the observation.identifier field is not set in an InsertResult operation. It is simple to work around this by assigning values directly in the database, but it would be useful to have the identifier assigned automatically by InsertResult requests.

**Comment by CarstenHollmann** [comment]
The InsertResult operations support the gml:identifier since commit 58aecc3.

On the other hand you can use the DeleteObservation 2.0 operation which allows to delete observations by procedure, observedPropertym featureOfInterest, offering and temporal filter.
