### ISSUE TITLE
How to store and handle mobile sensor data in SOS?

### ISSUE THREAD

**Issue by manuGil** [52North/SOS#522]
Is there a predefined way to register mobile sensors into the SOS database? It is my impression that the way to store spatial objects is as features of interest, which goes to a corresponding table in the database schema. However, a mobile sensor requires to register a spatial object (location) every time a observation is  made. Does the current database model offer such capabilities? Is there a practical example on how to handle observation from mobile sensors? Any hints or remarks are welcome.

**Comment by CarstenHollmann** [comment]
Hi Manuel,

you can use the [SOS Spatial Filtering Profile](https://wiki.52north.org/SensorWeb/SensorObservationServiceIVDocumentation#Spatial_Filtering_Profile) to store the location of each observation. 

The geoemtry of the featureOfInterest could represent the area of interest or you can omit the geometry and the 52N SOS creates a line string from the observation locations and uses this as featureOfInterest geometry.

In the examples of the 52N SOS Test Client you find an example (InsertObservation - Measurement/Spatial Filtering Profile).
The current [development](https://github.com/52North/SOS/tree/develop) version of the SOS also provides an InsertSensor example for a mobile sensor.

Best,
Carsten

**Comment by manuGil** [comment]
Hello Carsten,

Thank you for your reply. I will give it  a try.

Cheers,
