### ISSUE TITLE
Add DeleteResultTemplate operation

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/SOS#530]
Add a DeleteResultTemplate operation to support the deletion of a resultTemplate

**Comment by EHJ-52n** [comment]
Requirements:
- [ ] Operation should delete data in database
-  Implement support for the following encodings
   - [ ] SOAP
   - [ ] POX
   - [ ] KVP
 
Specification:
- Request structure:
  List of Identifier XOR offering + observed property
- Response structure:
  List of Identifier

Errors:
- Identifier/template not found (via cache) 404 -> invalid parameter exception
- Bad request 4xx (mix of identifier and/or offering/observed property)

Implementation:
- Get hibernate template objects and delete matching objects to be generic
