### ISSUE TITLE
No Support for OM_ComplexObservation using JSON?

### ISSUE THREAD

**Issue by manuGil** [52North/SOS#553]
I wrote my version of a InsertObservation using the Spatial Profile and the ComplexObservation type in JSON. I am using version 4.4.

However, the server replies with a 400 error and a message stating that the OM_ComplexObservation type is not supported.  The XML version of the request using SOAP+XML works fine.

** * Is this the case?** or 
I** * s it my version of the request wrong?** If yes, I would like to see an example 

### __This is the request:__

    { "request": "InsertObservation",
    "service": "SOS",
    "version": "2.0.0",
    "offering": "http://www.52north.org/test/offering/9",
    "observation": {
		"type": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation",
		"procedure": "http://www.52north.org/test/procedure/9",
		"resultTime": "2012-11-19T13:50:00+02:00",
		"parameter": {
			"NamedValue": {
				"value": {
					"type": "Point",
					"coordinates": [2, 1]
				},
				"name": "http://www.opengis.net/def/param-name/OGC-OM/2.0/samplingGeometry"
			}
		},
		"featureOfInterest": {
			"geometry": {
				"crs": {
					"type": "name",
					"properties": {
						"name": "EPSG:4326"
					}
				},
				"type": "Point",
				"coordinates": [2, 1]
			},
			"identifier": {
				"value": "http://www.52north.org/test/featureOfInterest/9",
				"codespace": "http://www.opengis.net/def/nil/OGC/0/unknown"
			},
			"sampledFeature": ["http://www.52north.org/test/featureOfInterest/world"],
			"name": [{
					"value": "Name for 9",
					"codespace": "http://www.opengis.net/def/nil/OGC/0/unknown"
				}
			]
		},
		"observedProperty": "http://www.52north.org/test/observableProperty/9_1",
		"phenomenonTime": "2012-11-19T13:50:00+02:00",
		"result": [{
				"identifier": "http://www.52north.org/test/observableProperty/9_1/length",
				"definition": "http://www.52north.org/test/observableProperty/9_1/length",
				"value": 30.5,
				"uom": "m",
				"type": "quantity",
				"name": "length"
			}, {
				"value": 20,
				"identifier": "http://www.52north.org/test/observableProperty/9_1/counting",
				"type": "count",
				"name": "counting",
				"definition": "http://www.52north.org/test/observableProperty/9_1/counting"
			}
		]
	} }

### This is the Server Response:

` { "version" : "1.1.0",
     "exceptions" : [
        {
          "code" : "InvalidRequest",
          "text" : "Unsupported observationType: http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_ComplexObservation"
        }
      ] }`

**Comment by CarstenHollmann** [comment]
Hi @manuGil,

the JSON binding/coding does not support all observationTypes the XML/SOAP+XML binding/encoding supports. So the complex types (OM_ComplexObservation, OM_SWEArrayObservation) are not yet supported by the JSON binding/encoding but the simple types (OM_Measurement, OM_CountObservation, ...) are supported.

The JSON binding/coding is not standardized but we have tried
to implement the JSON encoding against the abstract definitions of the
specifications (SOS 2.0, O&M 2.0, SWES 2.0).

**Comment by CarstenHollmann** [comment]
Added support in [this arctic-sea commit](https://github.com/52North/arctic-sea/commit/82a30efe217c6960a936cd584f8270a9dbc9b2b4)
Would be supported in SOS 5.1.1
