### ISSUE TITLE
Cannot install on Postgres: NullPointerException

### ISSUE THREAD

**Issue by mikevdg** [52North/SOS#558]
Build from origin/develop (same behaviour from 4.3.6); deploy to tomcat (8.0.30, yea I know), deploy the war, ...

Click "Click <a>here</a> to start", "[Start]" to configure, using "PostgreSQL/PostGIS", enter all details with mostly default values, click the next button. I get this 500 page::

    java.lang.NullPointerException
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	org.hibernate.tool.hbm2ddl.DatabaseMetadata.getTableMetadata(DatabaseMetadata.java:158)
	org.hibernate.tool.hbm2ddl.DatabaseMetadata.isTable(DatabaseMetadata.java:207)
	 org.n52.sos.ds.datasource.AbstractPostgresDatasource.checkSpatialRefSys(AbstractPostgresDatasource.java:166)
	org.n52.sos.ds.datasource.AbstractPostgresDatasource.validatePrerequisites(AbstractPostgresDatasource.java:142)
	org.n52.sos.ds.datasource.AbstractHibernateDatasource.validatePrerequisites(AbstractHibernateDatasource.java:584)
	org.n52.sos.web.install.InstallDatasourceController.process(InstallDatasourceController.java:78)
	org.n52.sos.web.install.AbstractProcessingInstallationController.post(AbstractProcessingInstallationController.java:69)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<snip>

I'm available to help debug this issue.

**Comment by CarstenHollmann** [comment]
Which PostgreSQL and PostGIS versions do you use?

I was not able to reproduce this with a build from the develop branch.

**Comment by mikevdg** [comment]
According to dpkg (Debian Linux), Postgres 9.6.3-3 and postgis 2.3.1+dfsg-2.

**Comment by mikevdg** [comment]
An SQLException is thrown but swallowed: `ERROR: column am.amcanorder does not exist
  Position: 407`. A message provided is `could not get table metadata: spatial_ref_sys`, but I think that's caused by the first isue. I haven't got a stack trace yet.

The NPE is caused by sqlExceptionConverter in SqlExceptionHandler.java:112 being null. Will investigate why.

**Comment by mikevdg** [comment]
Caused by Dialect.java:1749: the hibernate dialect is an instance of `PostgisDialect`, which returns null when buildSQLExceptionConverter() is invoked. This method is @deprecated in `Dialect` and if Netbeans isn't lying to me, there is no other implementation of this method.

**Comment by mikevdg** [comment]
It seems that the resolution of the swallowed exception is to upgrade to a newer version of hibernate (5.1.0 - is it backwards compatible?).

https://hibernate.atlassian.net/browse/HHH-9131 - now investigating whether hibernate can be upgraded.

In other news, my new database schema disappeared (!?). That's probably the root cause.

**Comment by mikevdg** [comment]
It looks like you have your own fork of hibernate-spatial.

This can be resolved by adding a buildSQLExceptionConverter() method to PostgisDialect - mark it as deprecated.

**Comment by CarstenHollmann** [comment]
Thanks for the detailed information.

With which version have you tested the deployment?

The SOS 4.3.6 does not work with PostgreSQL 9.6.x because the JDBC driver does not support this PostgreSQL version.

We have deployed the current develop branch with PostgreSQL 9.6.x, so this should work.
