### ISSUE TITLE
`mvn package -P oracle` fails to build

### ISSUE THREAD

**Issue by mikevdg** [52North/sos#559]
When trying `mvn package -U -P oracle -DskipTests=true`, I get::

    [ERROR] Failed to execute goal on project hibernate-datasource-oracle: Could not resolve dependencies for project org.n52.sensorweb.sos:hibernate-datasource-oracle:jar:4.4.1-SNAPSHOT: Could not find artifact com.oracle:ojdbc6:jar:11.2.0 in Apache (http://repo1.maven.org/maven2) -> [Help 1]

Indeed, looking at http://repo1.maven.org/maven2/com/oracle/, there is no ojdbc6, but there is ojdbc14 (which has a version of 10.2.0.4.0 - which is old???).

Perhaps Oracle didn't like it there and had it removed?

**Comment by CarstenHollmann** [comment]
Hi,

the Oracle JDBC driver are not provided via Maven due to the Oracle license.

Please read the 52N SOS wiki how to build the SOS from sources with Oracle:

https://wiki.52north.org/SensorWeb/SensorObservationServiceIVDocumentation#B1_41_Building_from_Source

Best,
Carsten

**Comment by mikevdg** [comment]
https://blogs.oracle.com/dev2dev/get-oracle-jdbc-drivers-and-ucp-from-oracle-maven-repository-without-ides

Has the SOS service been used with ojdbc version 12? To be honest, manually downloading the jar file looks simpler than using their repository.
