### ISSUE TITLE
mvn -Pconfigure-datasource fails to build

### ISSUE THREAD

**Issue by mikevdg** [52North/SOS#560]
Following instructions on https://wiki.52north.org/SensorWeb/SensorObservationServiceIVDocumentation#B1_41_Building_from_Source, using origin-develop::

    $ mvn -Pconfigure-datasource

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run
     (configure-datasource) on project webapp: An Ant BuildException has occured: Warning: 
    Could not find file /home/mikevdg/workspace/52North-git-origin-develop-ngmp/webapp 
    /${project.parent.basedir}/misc/conf/datasource.properties to copy.
    [ERROR] around Ant part ...<copy file="${project.parent.basedir}/misc/conf/datasource.properties" 
    tofile="/home/mikevdg/workspace/52North-git-origin-develop-ngmp/webapp/target/52n-sos-webapp
    /WEB-INF/datasource.properties"/>... @ 4:199 in /home/mikevdg/workspace/52North-git-origin-
    develop-ngmp/webapp/target/antrun/build-main.xml

I worked around this by changing webapp/pom.xml:15 from:

    <databaseConfigurationFile>${project.parent.basedir}/misc/conf/datasource.properties</databaseConfigurationFile>

to

     <databaseConfigurationFile>${project.basedir}/../misc/conf/datasource.properties</databaseConfigurationFile>

It seems that Maven no longer recognises project.parent?? Or perhaps my version of maven is old (3.3.9)?

**Comment by CarstenHollmann** [comment]
I will check this

**Comment by CarstenHollmann** [comment]
Hi @mikevdg,

you have to rename or copy and modify one of the provided `datasource.properties.XY.templates` to `datasource.properties`  if you use the `configure-datasource` profile during the build.
