### ISSUE TITLE
Sensors disappear

### ISSUE THREAD

**Issue by oggioniale** [52North/SOS#571]
After the insertSensor request, by client, the sensor appear in the Describe Sensor and in all parts of Capability. When the cache restarted by the server the procedure disappear from all parts of capability. I tested for:
"sos": "4.3.15" and "4.4.0",
"tomcat": "  7.0.52.0",
"postgresql": "9.3.18",
"postgis": "2.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1"

**Comment by CarstenHollmann** [comment]
See #566
