### ISSUE TITLE
docker-compose - bad configuration for the nginx port on the host

### ISSUE THREAD

**Issue by pmauduit** [52North/SOS#578]
Trying the docker composition, I noticed that the nginx container was listening on the port 81 of the host, instead of 80. I first thought it was intentional, but every redirects during the setup wizard were broken, trying to redirect my browser onto `:80` instead of `:81`:

https://github.com/52North/SOS/blob/develop/docker/docker-compose.yml#L52

Is this just a typo ? The fix is fairly trivial, one just need to change the `81` into `80`.

**Comment by EHJ-52n** [comment]
@pmauduit thanks for pointing is out. I'll fix it. Thank you!
