### ISSUE TITLE
Creating a permlink is not working for +2000 chars

### ISSUE THREAD

**Issue by Effizjens** [52North/SOS#590]
I recognized that the permalink function in the SOS Test Client is broken for long XMLrequests. You can find a HTML file attached here with just a small script (it doesn't look very fancy, sorry for that) to show you the limit of the prompt window to 2000 chars.
"[POX] GetObservation (SOS 2.0.0)" for example is too long by default.
There will be no error, but the XML request contains "..." and is shortert than the original one.
[Chars_of_Prompt.zip](https://github.com/52North/SOS/files/1629294/Chars_of_Prompt.zip)

Also the createPermalink function in the client.js is missing a "//". If you create a permalink, it will begin with "http:geo...". "document.location.protocol" only contains "http:" so it should be "document.location.protocol+"//". Nevertheless it works, if you copy it to a browser.

**Comment by CarstenHollmann** [comment]
hi @Effizjens,

thanks for pointing to this issue.

Which browser do you use?
 I guess Chrome because Chrome has a limitation of 2000 chars for the prompt window.
Firefox allows more characters and the permalink creation works with that.
