### ISSUE TITLE
What's the default username/password for admin?

### ISSUE THREAD

**Issue by francbartoli** [52North/SOS#611]
Are those credentials already configured when I land to the admin menù after having deployed the war to tomcat?
I was assuming admin/password but that doesn't work

**Comment by CarstenHollmann** [comment]
The username/password for the admin interface would be defined at the end of the installation process.

After you have deployed the war to tomcat you have to execute the installation process which is started by clicking on **`here`** in the red info message: `You first have to complete the installation process! Click here to start it.`

**Comment by francbartoli** [comment]
Thanks @CarstenHollmann, what about if I want to do it programmatically? For instance within a docker container.

**Comment by francbartoli** [comment]
@CarstenHollmann I found sql/reset_admin.sql script and then everything makes sense. Further question is what's the hash to be used for overriding the value?

**Comment by CarstenHollmann** [comment]
BCrypt is used to de-/encode the password. 

Here is the link to an online BCrypt de-/encoder: https://bcrypt-generator.com/

**Comment by francbartoli** [comment]
thanks @CarstenHollmann it helps a lot
