### ISSUE TITLE
insertSensor request create 2 sensors

### ISSUE THREAD

**Issue by oggioniale** [52North/SOS#612]
After the insertSensor request (for sensor http://www.52north.org/test/procedure/9), by client, in the capability appear two sensors: http://www.52north.org/test/procedure/1 and http://www.52north.org/test/procedure/9. I installed SOS from doker hub.
I tested for:
SOS version: 4.4.0
Revision: 83241c9336c90a607f9699f4ece69128cbdece89

**Comment by EHJ-52n** [comment]
Thank you for your feedback @oggioniale.

Could you please link the example request that you used to insert the sensor, or if you created the request by your own, please post the message you send to the server.
