### ISSUE TITLE
SQL scripts to create the database from scratch

### ISSUE THREAD

**Issue by francbartoli** [52North/SOS#613]
I need to get the goal to have a fully configured SOS environment after a docker-compose bootstrap. I'm going to use 4.3.8 version.
I've defined my own dockerfile and used this create script [https://github.com/52North/ConnectinGEO/blob/master/sos-envirocar-database/envirocar-postgres/sos_db_create.sql](https://github.com/52North/ConnectinGEO/blob/master/sos-envirocar-database/envirocar-postgres/sos_db_create.sql) but when trying to creare a sensor using the example request from client the following error is raised:

`Unexpected exception <?xml version=“1.0” encoding=“UTF-8"?>↵<ows:ExceptionReport xmlns:ows=“http://www.opengis.net/ows/1.1” xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” version=“2.0.0” xsi:schemaLocation=“http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd”>↵  <ows:Exception exceptionCode=“NoApplicableCode”>↵    <ows:ExceptionText>Error while inserting sensor data into database!↵[EXEPTION]: ↵could not extract ResultSet</ows:ExceptionText>↵  </ows:Exception>↵</ows:ExceptionReport>`

Also at the database level I'm facing with:

```
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:  SELECT 1
ERROR:  column this_.hibernatediscriminator does not exist at character 268
STATEMENT:  select this_.observablePropertyId as observab1_13_0_, this_.identifier as identifi3_13_0_, this_.codespace as codespac4_13_0_, this_.name as name5_13_0_, this_.codespaceName as codespac6_13_0_, this_.description as descript7_13_0_, this_.disabled as disabled8_13_0_, this_.hibernateDiscriminator as hibernat2_13_0_ from public.observableProperty this_ where this_.identifier in ($1, $2)
```

It seems to be something is missing so which is the right sql scripts to execute from the web archive of that version? Different folders are confusing me:

![image](https://user-images.githubusercontent.com/560676/38696191-bf1ebfce-3e8e-11e8-9ea9-2a98f9df5d5c.png)

**Comment by CarstenHollmann** [comment]
Hi,

maybe there is an issue in the SQL script you have mentioned.

But you can use the SQL create script for PostgreSQL from the original 52N SOS repository in the maintenance branch for SOS 4.3.x:

https://github.com/52North/SOS/blob/maintenance/4.3/misc/db/PostgreSQL/series/PG_series_script_create.sql

The created database model works with the 52N SOS 4.3.8 and later 4.3.x versions.
