### ISSUE TITLE
Interconnection with other SOS services

### ISSUE THREAD

**Issue by nicolas-f** [52North/SOS#619]
Hi,
I have several SOS instances deployed on multiple servers. Does 52North allow to retrieve (pull) measurements to a main SOS 52 North server ?

**Comment by ridoo** [comment]
The only orchestrate feature I am aware of is to proxy available instances via the [Sensor Web REST API](https://github.com/52North/series-rest-api) which is shipped by the SOS Web application. The proxy is available from https://github.com/52North/restful-timeseries-proxy. Please note, that this is rather old version and we are working on a re-implementation of it, but priorities lay elsewhere at the moment.

However, having such a proxy deployed can configure several SOS instances within a [sos instances config file](https://github.com/52North/restful-timeseries-proxy/blob/master/webapp/src/main/webapp/ds/sos-instances.data.xml). The metadata of each SOS is harvested and cached regularly.

Please be aware that the described solutions does not orchestrate SOS instances in terms of a gateway (accessing these SOS instances from another SOS interface), but to expose a lightweight RESTful interface on top of several SOS instances.

Hope this helps.

**Comment by nicolas-f** [comment]
I understand thank you
