### ISSUE TITLE
Settings on Different Instances

### ISSUE THREAD

**Issue by marcogrieco** [52North/SOS#639]
Hi,
i have installed North52 on an architecture with 2 nodes (instances) and a balancer in front of them but i have a question. All data about sensors are stored in a DB, in my case Oracle. The two nodes have the same DB Instance, so if i call the webservices on a node or the other the response is the same. The problem is that alla data about settings (for example Service Provider) are not stored in Oracle, so if i modify some data on a node i must replicate the same data on the other node. The informations are not centralized. There is a way to share also this informations without replace them manually?

Thanks in advance.

Marco

**Comment by CarstenHollmann** [comment]
Hi Marco,
you can export the settings via the admin interface and import the settings during the installation process (`Upload a previous configuration file`). Another option is to copy the `configuration.db` file from one instance to the other instance, located in the deployed SOS instance folder.

Best,
Carsten
