### ISSUE TITLE
Reload Capabilities Cache - 4.4.0

### ISSUE THREAD

**Issue by marcogrieco** [52North/SOS#640]
Hi,
i'm using the version 4.4.0 of North52 but i'm having different errors about cache. If i insert a sensor and call the methods GetCapabilities or DescribeSensor the sensor appear in the results but if i do a "Reload Capabilities Cache" before the call, then the responses are empty or wrong (for example invalid parameter for DescribeSensor). Why? The cache is not working as expected. How can i solve this issue on this release?

Thanks in advance.

**Comment by CarstenHollmann** [comment]
Hi Marco.,
I have tested this with the InsertSensor SensorML 2.0 exmaple from the client and can not reproduce the issue you have described. 
So I have 
- executed ÌnsertSensor`
- executed a `DescribeSensor`
- run `Reload Capabilities Cache`
- executed again the `DescribeSensor` and compared it with the previous 

Both DescribeSensor results looked the same.

Have you detected this behavior with the set-up you described in the issue #639?

Best,
Carsten

**Comment by marcogrieco** [comment]
Hi Carsten,
have you used the same version as described in my post? I'm using the 4.4.0 version of North52.
Moreover, how can i detect if there are problems with the cache writing?

I have detected this behavior working only with one instance.

Thanks in advance.

Marco

**Comment by marcogrieco** [comment]
Probably the problem is that the procedure have not registered observations, so the getCapabilities does not return any procedures. Is this a problem? When you insert a new procedure the getCapabilities return it but if you reload the cache and the procedure has not the observations it is not loaded in the cache. 

Thanks.
