### ISSUE TITLE
docker hub update

### ISSUE THREAD

**Issue by lukejpreston** [52North/SOS#649]
Noticed https://hub.docker.com/r/52north/sos hasn't been updated in a while, is it possible to get someone to update this with the latest bug fixes etc.?

**Comment by CarstenHollmann** [comment]
Hi @lukejpreston ,

we have updated the SOS images on [docker hub](https://hub.docker.com/r/52north/sos).

In the new [Docker section](https://github.com/52North/SOS#docker) of the readme you can find some more information about the images.

Best,
Carsten
