### ISSUE TITLE
/client?load=exampleData not working in SOS 5.0.0-alpha.5

### ISSUE THREAD

**Issue by EHJ-52n** [52North/SOS#656]
I deployed the alpha-5 release of the 5.0:

> Version: 5.0.0-alpha.5
> Branch: b6881b29a8649c0b4cabb570cef5d8f79ac43dc4
> Revision: b6881b29a8649c0b4cabb570cef5d8f79ac43dc4
> Build date: 2019-06-13 08:31:45+0000
> Installation date: 2019-06-13 08:31:45+0000

Browser:
> Chromium Version 74.0.3729.169 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

When clicking on the "Test client"-Link (`/client?load=exampleData`) on the administrator index page, I am redirected to the form test client and the following error message is shown:

> The specified request could not be found or is not supported.

On the server, the file `/static/conf/client-config.json` contains a collection of requests with the matching id:
```json
[...]
{
	"id":"exampleData",
	"service":"SOS",
	"version":"2.0.0",
	"method":"POST",
	"binding": "application/json",
	"headers":{
		"Accept":"application/json",
		"Content-Type":"application/json"
	},
	"operation":"Batch",
	"title":"Example Data",
	"requiredOperations":[
[...]
```

Do you need any additional information?

**Comment by CarstenHollmann** [comment]
Which `database concept` do you use?

If you have not selected `transactional database model` the insertion of the example data is not possible.

**Comment by CarstenHollmann** [comment]
See previous explanation
