### ISSUE TITLE
Can not delete offering

### ISSUE THREAD

**Issue by lukejpreston** [52North/SOS#658]
I am using SOS 4.4.8 (and checked ono release candidate)

If I have already inserted a sensor with an id of `id` and I want to completely remove it.

First I remove all the observations using the following XML (I do in it chunks of time in order to speed up deleting all the observations)

```
<?xml version="1.0" encoding="UTF-8"?>
<sosdo:DeleteObservation
    xmlns:sosdo="http://www.opengis.net/sosdo/2.0"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:swes="http://www.opengis.net/swes/2.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" service="SOS" xsi:schemaLocation="http://www.opengis.net/sosdo/2.0 http://52north.org/schema/sosdo/2.0/sosdo.xsd">
    <sosdo:procedure>{{id}}</sosdo:procedure>
    <sosdo:temporalFilter>
        <fes:During>
            <fes:ValueReference>phenomenonTime</fes:ValueReference>
            <gml:TimePeriod gml:id="tp_1">
                <gml:beginPosition>{{beginPosition}}</gml:beginPosition>
                <gml:endPosition>{{endPosition}}</gml:endPosition>
            </gml:TimePeriod>
        </fes:During>
    </sosdo:temporalFilter>
</sosdo:DeleteObservation>
```

Then I remove the sensor using the following XML

```xml
<?xml version="1.0" encoding="UTF-8"?>
<swes:DeleteSensor xmlns:swes="http://www.opengis.net/swes/2.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="SOS" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/swes/2.0 http://schemas.opengis.net/swes/2.0/swes.xsd">
    <swes:procedure>{{id}}</swes:procedure>
</swes:DeleteSensor>
```

Then I remove the result template using the following XML

```xml
<?xml version="1.0" encoding="UTF-8"?>
<drt:DeleteResultTemplate xmlns:drt="http://www.opengis.net/drt/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="SOS" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/drt/1.0 https://52north.org/schema/sosdrt/1.0/sosdrt.xsd">
    <drt:resultTemplate>{{id}}/template/1</drt:resultTemplate>
</drt:DeleteResultTemplate>
```

This successfully removes the sensor and all the data, then if I want to insert the same sensor I get an error, something along the lines of ` The offering with the identifier 'id/offering' still exists`

I found if I run this SQL it removes the offering. I would rather do this through the SOS service

`X` is the id from the offering table

```sql
DELETE FROM offering where identifier='id/offering';
DELETE FROM offeringallowedfeaturetype WHERE offeringid=X;
DELETE FROM offeringallowedobservationtype WHERE offeringid=X;
DELETE FROM series WHERE offeringid=X;
```

My questions are
* is this a bug?
* should I be doing some other restful calls I don't know about?
* if this is desired behaviour what would you suggest I do when readding a sensor that was previously removed?

**Comment by CarstenHollmann** [comment]
Hi @lukejpreston,

I have checked this with the release candidate (the mentioned operations and work flows are not modified in the release candidate since version 4.4.8) but I was not able to reproduce this behavior.
I have inserted a sensor, observation and relsult template and then deleted it. The re-insertion of the sensor works as expected.

In some cases the local cache update was not quite finished after the deletion and before you insert the sensor again. What you can do is to execute the `Relaod Capabilites Cache` before you insert the sensor again.

The DeleteSensor and DeleteObservaiton operations do no delete the data physically from the database but the operations mark the data only with the deleted flag. Via the admin interface you can delete the deleted observation physically ( `Datasource Maintenance -> Delete Deleted Observations`) but the deleted procedure, ... can not be deleted from the datavase via the SOS yet.

**Comment by lukejpreston** [comment]
Thanks for the reply, I will update my SOS to the latest version and try those two buttons. I will also see about creating some steps to reproduce the error.

**Comment by lukejpreston** [comment]
Neither of those buttons helped, I will see about creating the steps for you

**Comment by lukejpreston** [comment]
I am not sure how to reproduce this. For whatever reason, the SOS instance starts erroring on that it can not find the feature of interest, then it refuses to remove the offering.

I have added versions to my sensors which gets around this issue since each new versioned sensor has a new offering.

If I can work out what happened to get the service into this state I will reopen this issue but it seems intermittent.
