### ISSUE TITLE
unable to export data in Helgoland 

### ISSUE THREAD

**Issue by danielMihaiToma** [52North/SOS#662]
I try to export CSV data in Helgoland client form the SOS server and is not working:
http://nexos.demo.52north.org/52n-sos-nexos-test/api/timeseries/68/getData.zip?generalize=false&timespan=2017-09-04T23%3A59%3A59%2B02%3A00%2F2017-09-05T23%3A59%3A59%2B02%3A00&locale=en&zip=true&bom=true

This is the error I get: {"statusCode":500,"reason":"Internal Server Error","developerMessage":"Unparsable language parameter: en-GB,en;q=0.9,es-ES;q=0.8,es;q=0.7,ca-ES;q=0.6,ca;q=0.5,ro-RO;q=0.4,ro;q=0.3,en-US;q=0.2","userMessage":"Unexpected Exception occured."}

**Comment by CarstenHollmann** [comment]
This issue concerns the REST-API and the issue was alread fixed in latter versions of the REST-API, see https://github.com/52North/series-rest-api/issues/450
