### ISSUE TITLE
GetResultTemplate JSON

### ISSUE THREAD

**Issue by EnocMartinez** [52North/SOS#837]
When using the request GetResultTemplate in JSON (complex observationi with several fields), the SOS  (version 4.4.14) returns this error:
```json
{
  "version": "1.1.0",
  "exceptions": [
    {
      "code": "NoApplicableCode",
      "text": "org.n52.sos.ogc.swe.SweField can not be encoded by Encoder org.n52.sos.encode.json.impl.FieldEncoder because it is not yet implemented!"
    }
  ]
}
```
In XML encoding it works fine

**Comment by CarstenHollmann** [comment]
As the exception mentioned a field element is not yet supported by the encoder.

It would be great if you would be able to provide us the XML template to check which element is not yet supported

Thanks

**Comment by EnocMartinez** [comment]
Attached you can find a zip file [transactions_sbe37.zip](https://github.com/52North/SOS/files/4750955/transactions_sbe37.zip) with the transactions.

**Comment by EnocMartinez** [comment]
Now it works!
Thanks a lot
