### ISSUE TITLE
Duplicated 'admin' segment in the URL

### ISSUE THREAD

**Issue by ghobona** [52North/SOS#999]
During installation, if the database has not been populated, this page http://localhost:8080/52n-sos-webapp/admin/datasource/ links to http://localhost:8080/52n-sos-webapp/admin/admin/operations.
![VirtualBox_CITE_02_02_2021_15_12_24](https://user-images.githubusercontent.com/18121038/106620275-519ac100-6569-11eb-94a6-96ed1740cbb4.png)

Note the duplicated 'admin' segment in the URL.

The page should be linking to this instead http://localhost:8080/52n-sos-webapp/admin/operations

**Comment by CarstenHollmann** [comment]
Which SOS release version do you use?

In the current release version (5.3.1) the URL looks correct.

**Comment by ghobona** [comment]
I cloned the repo and built the SOS from source yesterday (2021-02-03). The pom file says it is version 5.3.2-SNAPSHOT

**Comment by CarstenHollmann** [comment]
I have build the SOS from the (default) develop branch (5.3.2-SNAPSHOT) and the URL locks correct.

**Comment by ghobona** [comment]
Ok, thanks. Perhaps it was something I missed during the configuration.

I'm happy to close this issue.
